version: '3'
services:
  ruby:
    build:
      context: .
    container_name: ruby-linebot
    ports:
      - 8888:4567
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true
    command: >
      sh -c "
        bundle install
        bundle exec ruby app.rb
      "
